### ISSUE TITLE
Getting this warning: Requires Babel "^7.0.0-0", but was loaded with "6.26.3".

### ISSUE THREAD

**Issue by Jezfx** [flexdinesh/react-npm-package-boilerplate#5]
Running `npm run test` gave me this warning: 
`Requires Babel "^7.0.0-0", but was loaded with "6.26.3".` and stopped the tests from running. 

I was able to fix it by adding `"babel-core": "^7.0.0-bridge.0",` to the devDependencies (as well as resolutions which you already have). 

Happy to open a PR if you want me to(?)

**Comment by flexdinesh** [comment]
@Jezfx I already tried that and it didn't work. There was an open issue in the babel repo relevant to this when I tried that and adding **resolutions** was a temporary fix as `resolutions` will work only with `yarn` and not `npm`.

If  adding `"babel-core": "^7.0.0-bridge.0"` without `resolutions` fixes this error, please feel free to create a PR. But if you need to add `resolutions`, then it's the same and probably adding `"babel-core": "^7.0.0-bridge.0"` doesn't have any effect at all.

The goal is to get this working with `npm` without having to use `resolutions` and `yarn`.

**Comment by Jezfx** [comment]
I think I needed `resolutions` too. I'll close the issue. thanks anyway.
